### ISSUE TITLE
Please add a different installation method

### ISSUE THREAD

**Issue by zblesk** [Airsequel/SQLiteDAV#9]
This looks like a cool tool and I'd like to try it, but I really don't want to install yet another stack and all that stuff. 
Could you maybe consider providing a binary (windows or linux both fine by me), or a docker container?

Thank you.

**Comment by ad-si** [comment]
Hi, I added binaries for Linux and macOS to the latest release: https://github.com/Airsequel/SQLiteDAV/releases/tag/0.1.1.0

Does that work for you?

**Comment by zblesk** [comment]
Thanks! I guess it did technically run, even though I only go 404s out of it.
